from django.contrib import admin
from .models import Members,Available_Players,Transfer_History,Challenges,Admin_Setup,About_Game,Term_Condition,Game_Delay_Report,Notifications,Leaderboard,Tournaments,All_Messages,All_Chats,Withdrawals

admin.site.register([Members,Available_Players,Transfer_History,Challenges,Admin_Setup,About_Game,Term_Condition,Game_Delay_Report,Notifications,Leaderboard,Tournaments,All_Messages,All_Chats,Withdrawals])
