# Generated by Django 4.0.2 on 2023-04-20 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='All_Gtt_Whot_Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(blank=True, max_length=100, null=True)),
                ('card_shape', models.CharField(blank=True, max_length=100, null=True)),
                ('card_image', models.ImageField(blank=True, null=True, upload_to='All_Gtt_Whot_Cards')),
            ],
        ),
        migrations.CreateModel(
            name='Gtt_Whot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_one', models.CharField(blank=True, max_length=100, null=True)),
                ('player_one_number_of_cards', models.CharField(blank=True, max_length=1000, null=True)),
                ('player_two', models.CharField(blank=True, max_length=100, null=True)),
                ('player_two_number_of_cards', models.CharField(blank=True, max_length=1000, null=True)),
                ('general_market', models.ManyToManyField(blank=True, related_name='General_Market', to='gttWhott.All_Gtt_Whot_Cards')),
                ('player_one_cards', models.ManyToManyField(blank=True, related_name='Player_One', to='gttWhott.All_Gtt_Whot_Cards')),
                ('player_two_cards', models.ManyToManyField(blank=True, related_name='Player_Two', to='gttWhott.All_Gtt_Whot_Cards')),
            ],
        ),
    ]
