# Generated by Django 5.2 on 2025-05-01 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gttWhott', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtt_whot',
            name='game_timer',
            field=models.IntegerField(blank=True, default=15, null=True),
        ),
    ]
