# Generated by Django 4.0.2 on 2023-04-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gttWhott', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtt_whot',
            name='number_of_general_market',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
