# Generated by Django 5.2 on 2025-05-01 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gttWhott', '0002_gtt_whot_game_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gtt_whot',
            name='game_timer',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
    ]
