# Generated by Django 4.0.2 on 2023-04-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gttWhott', '0003_alter_all_gtt_whot_cards_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_gtt_whot_cards',
            name='card_image',
            field=models.ImageField(blank=True, null=True, upload_to='All_Gtt_Whot_Cards'),
        ),
    ]
