# Generated by Django 4.0.2 on 2023-04-22 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gttWhott', '0004_alter_all_gtt_whot_cards_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtt_whot',
            name='current_card',
            field=models.ManyToManyField(blank=True, related_name='Current_Card', to='gttWhott.All_Gtt_Whot_Cards'),
        ),
    ]
