# Generated by Django 4.0.2 on 2023-04-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gttWhott', '0005_gtt_whot_current_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtt_whot',
            name='game_charges',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
