# Generated by Django 4.0.2 on 2023-04-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gttWhott', '0006_gtt_whot_game_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtt_whot',
            name='to_play',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
