# Generated by Django 4.0.2 on 2023-04-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gttWhott', '0007_gtt_whot_to_play'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtt_whot',
            name='gamee_reload',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
