# Generated by Django 4.0.2 on 2023-04-30 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gttWhott', '0008_gtt_whot_gamee_reload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gtt_whot',
            old_name='gamee_reload',
            new_name='game_reload',
        ),
    ]
