# Generated by Django 4.0.2 on 2023-05-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gttWhott', '0009_rename_gamee_reload_gtt_whot_game_reload'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_gtt_whot_cards',
            name='has_power',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='all_gtt_whot_cards',
            name='requirement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
