# Generated by Django 4.0.2 on 2023-05-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gttWhott', '0010_all_gtt_whot_cards_has_power_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtt_whot',
            name='how_many_required_to_pick',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='gtt_whot',
            name='player_required_to_pick',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='gtt_whot',
            name='required_to_pick',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
