# Generated by Django 4.0.2 on 2023-05-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gttWhott', '0011_gtt_whot_how_many_required_to_pick_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gtt_whot',
            name='how_many_required_to_pick',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
