# Generated by Django 4.0.2 on 2023-05-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gttWhott', '0012_alter_gtt_whot_how_many_required_to_pick'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtt_whot',
            name='game_winner',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='gtt_whot',
            name='has_tie',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
