# Generated by Django 4.0.2 on 2023-05-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gttWhott', '0013_gtt_whot_game_winner_gtt_whot_has_tie'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtt_whot',
            name='game_finished',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
