# Generated by Django 4.0.2 on 2023-05-05 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gttWhott', '0015_gtt_whot_can_play'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gtt_whot',
            old_name='can_play',
            new_name='user_can_play',
        ),
    ]
