# Generated by Django 4.0.2 on 2023-05-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gttWhott', '0016_rename_can_play_gtt_whot_user_can_play'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtt_whot',
            name='counted_cards',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
