# Generated by Django 4.0.2 on 2023-05-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gttWhott', '0017_gtt_whot_counted_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtt_whot',
            name='player_one_amount_of_cards',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='gtt_whot',
            name='player_two_amount_of_cards',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
