# Generated by Django 4.0.2 on 2023-05-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gttWhott', '0018_gtt_whot_player_one_amount_of_cards_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtt_whot',
            name='game_concluded',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
