# Generated by Django 4.0.2 on 2023-05-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gttWhott', '0019_gtt_whot_game_concluded'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtt_whot',
            name='player_paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
