# Generated by Django 4.0.2 on 2023-05-09 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gttWhott', '0020_gtt_whot_player_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gtt_whot',
            old_name='player_paid',
            new_name='player_won',
        ),
    ]
