# Generated by Django 4.0.2 on 2023-05-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gttWhott', '0021_rename_player_paid_gtt_whot_player_won'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtt_whot',
            name='hold_on',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
