# Generated by Django 4.0.2 on 2024-05-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gttWhott', '0022_gtt_whot_hold_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtt_whot',
            name='game_time',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
    ]
