# Generated by Django 4.0.2 on 2024-05-10 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gttWhott', '0023_gtt_whot_game_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('opponent', models.CharField(blank=True, max_length=100, null=True)),
                ('game_id', models.IntegerField(blank=True, default=0, null=True)),
                ('user_card', models.CharField(blank=True, max_length=100, null=True)),
                ('exchanged_card', models.CharField(blank=True, max_length=100, null=True)),
                ('challenge_stake_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('challenge_winning_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
        ),
    ]
