# Generated by Django 4.0.2 on 2023-03-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Black_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=1000, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
