# Generated by Django 4.2.16 on 2025-04-17 12:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(blank=True, max_length=1000, null=True)),
                ('about', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Admin_Setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_registered_members', models.IntegerField(blank=True, default=0, null=True)),
                ('min_game_charges', models.IntegerField(blank=True, default=50, null=True)),
                ('max_game_charges', models.IntegerField(blank=True, default=100, null=True)),
                ('transfer_charges', models.IntegerField(blank=True, default=100, null=True)),
                ('withdrawal_charges', models.IntegerField(blank=True, default=100, null=True)),
                ('deposit_link', models.CharField(blank=True, default='https://wa.me/7019462683?text=Hi%20Please%20I%20Want%20To%20Deposit', max_length=1000, null=True)),
                ('withdrawal_link', models.CharField(blank=True, default='https://wa.me/7019462683?text=Hi%20Please%20I%20Want%20To%20Withdraw', max_length=1000, null=True)),
                ('no_of_golden_number_played', models.IntegerField(blank=True, default=0, null=True)),
                ('no_of_golden_Whot_played', models.IntegerField(blank=True, default=0, null=True)),
                ('today', models.IntegerField(blank=True, default=0, null=True)),
                ('today_number_of_games', models.IntegerField(blank=True, default=0, null=True)),
                ('admin_whot_game_time', models.IntegerField(blank=True, default=30, null=True)),
                ('admin_international_registration_link', models.CharField(blank=True, default='https://wa.me/7019462683?text=Hi,Not%20A%20Nigerian,%20Please%20I%20Want%20To%20Register', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='All_Phone_Numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=1000, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Available_Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=1000, null=True)),
                ('stake_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('win_ratio', models.IntegerField(blank=True, default=0, null=True)),
                ('game_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_photo', models.BooleanField(blank=True, default=False, null=True)),
                ('time_available', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('game_type', models.CharField(blank=True, max_length=1000, null=True)),
                ('whatsapp_link', models.CharField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Challenges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenger', models.CharField(blank=True, max_length=1000, null=True)),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('challenge_game_type', models.CharField(blank=True, max_length=1000, null=True)),
                ('challenged', models.CharField(blank=True, max_length=1000, null=True)),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game_Delay_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter', models.CharField(blank=True, max_length=1000, null=True)),
                ('report', models.CharField(blank=True, max_length=1000, null=True)),
                ('time_reported', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(blank=True, max_length=1000, null=True)),
                ('notification_message', models.TextField(blank=True, default=None, null=True)),
                ('notification_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Term_Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(blank=True, max_length=1000, null=True)),
                ('terms', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(blank=True, max_length=1000, null=True)),
                ('sender_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('receiver_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('amount', models.CharField(blank=True, max_length=1000, null=True)),
                ('charges', models.CharField(blank=True, max_length=1000, null=True)),
                ('transaction_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('net_balance', models.CharField(blank=True, default='Out-Dated', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_password', models.TextField(blank=True, default=None, null=True)),
                ('is_special', models.BooleanField(blank=True, default=False, null=True)),
                ('gender', models.CharField(blank=True, max_length=1000, null=True)),
                ('balance', models.FloatField(blank=True, default=0, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=1000, null=True)),
                ('number_of_play', models.IntegerField(blank=True, default=0, null=True)),
                ('number_of_draw', models.IntegerField(blank=True, default=0, null=True)),
                ('number_of_win', models.IntegerField(blank=True, default=0, null=True)),
                ('number_of_loss', models.IntegerField(blank=True, default=0, null=True)),
                ('win_ratio', models.IntegerField(blank=True, default=0, null=True)),
                ('is_available', models.BooleanField(blank=True, default=False, null=True)),
                ('available_id', models.IntegerField(blank=True, default=0, null=True)),
                ('has_transfer', models.BooleanField(blank=True, default=False, null=True)),
                ('admin_charge', models.FloatField(blank=True, default=0, null=True)),
                ('user_game_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('has_clicked_missed_challenges', models.BooleanField(blank=True, default=False, null=True)),
                ('has_game', models.BooleanField(blank=True, default=False, null=True)),
                ('is_challenger', models.BooleanField(blank=True, default=False, null=True)),
                ('current_opponent', models.CharField(blank=True, max_length=1000, null=True)),
                ('challenge_expiry_time', models.DateTimeField(blank=True, null=True)),
                ('current_challenge_amount', models.FloatField(blank=True, default=0, null=True)),
                ('current_game_id', models.IntegerField(blank=True, default=0, null=True)),
                ('game_started', models.BooleanField(blank=True, default=False, null=True)),
                ('current_game_wining_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('number_of_reports', models.IntegerField(blank=True, default=0, null=True)),
                ('is_blacklisted', models.BooleanField(blank=True, default=False, null=True)),
                ('current_game_type', models.CharField(blank=True, max_length=1000, null=True)),
                ('current_number_of_whott_cards', models.IntegerField(blank=True, default=0, null=True)),
                ('shuffling_starting_game_on_progress', models.BooleanField(blank=True, default=False, null=True)),
                ('shuffling_check', models.BooleanField(blank=True, default=False, null=True)),
                ('missed_challenges', models.ManyToManyField(blank=True, related_name='Missed_Challenges', to='main.challenges')),
                ('my_challenges', models.ManyToManyField(blank=True, related_name='My_Challenges', to='main.challenges')),
                ('notifications', models.ManyToManyField(blank=True, to='main.notifications')),
                ('report_history', models.ManyToManyField(blank=True, to='main.game_delay_report')),
                ('transaction_history', models.ManyToManyField(blank=True, to='main.transfer_history')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
