# Generated by Django 4.0.2 on 2023-01-08 00:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transation_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(blank=True, max_length=1000, null=True)),
                ('sender_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('receiver_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('amount', models.FloatField(blank=True, default=0, null=True)),
                ('charges', models.FloatField(blank=True, default=0, null=True)),
                ('transaction_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(blank=True, default=0, null=True)),
                ('number_of_played', models.IntegerField(blank=True, default=0, null=True)),
                ('number_of_win', models.IntegerField(blank=True, default=0, null=True)),
                ('number_of_loss', models.IntegerField(blank=True, default=0, null=True)),
                ('win_ratio', models.IntegerField(blank=True, default=0, null=True)),
                ('transaction_history', models.ManyToManyField(to='main.Transation_History')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
