# Generated by Django 4.0.2 on 2023-01-08 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='transaction_history',
            field=models.ManyToManyField(blank=True, null=True, to='main.Transation_History'),
        ),
    ]
