# Generated by Django 4.2.16 on 2025-04-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='All_Phone_Numbers',
        ),
        migrations.RemoveField(
            model_name='members',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='members',
            name='country',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
