# Generated by Django 4.0.2 on 2023-01-08 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_members_transaction_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='gender',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
