# Generated by Django 4.2.16 on 2025-04-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_all_phone_numbers_remove_members_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer_history',
            name='transaction_topic',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
