# Generated by Django 4.2.16 on 2025-04-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_transfer_history_transaction_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available_players',
            name='time_available',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='game_delay_report',
            name='time_reported',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='transfer_history',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
