# Generated by Django 4.0.2 on 2023-01-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_members_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='number_of_played',
            new_name='number_of_play',
        ),
        migrations.AlterField(
            model_name='members',
            name='transaction_history',
            field=models.ManyToManyField(blank=True, to='main.Transation_History'),
        ),
    ]
