# Generated by Django 4.0.2 on 2023-01-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_number_of_played_members_number_of_play_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='All_Profile_photos')),
            ],
        ),
        migrations.RenameModel(
            old_name='Transation_History',
            new_name='Transfer_History',
        ),
        migrations.AddField(
            model_name='members',
            name='profile_photo',
            field=models.ManyToManyField(blank=True, to='main.Profile_Photo'),
        ),
    ]
