# Generated by Django 4.2.16 on 2025-04-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_available_players_time_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='is_seen',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
