# Generated by Django 4.0.2 on 2023-01-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='uploaded_photo',
            field=models.BooleanField(default=False),
        ),
    ]
