# Generated by Django 4.2.16 on 2025-04-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_notifications_is_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(blank=True, default=0, null=True)),
                ('username', models.CharField(blank=True, max_length=1000, null=True)),
                ('game', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('tournament_prize', models.IntegerField(blank=True, default=0, null=True)),
                ('tournament_entry_fee', models.IntegerField(blank=True, default=0, null=True)),
                ('number_slot', models.IntegerField(blank=True, default=0, null=True)),
                ('number_slot_taken', models.IntegerField(blank=True, default=0, null=True)),
                ('tournament_date', models.DateTimeField(auto_now_add=True)),
                ('tournament_link', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
