# Generated by Django 4.2.16 on 2025-04-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_leaderboard_tournaments'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
