# Generated by Django 4.0.2 on 2023-01-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_members_uploaded_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Available_Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000)),
                ('profile_photo', models.ImageField(upload_to='available_players_photos')),
                ('stake_amount', models.IntegerField(default=0)),
                ('win_ratio', models.IntegerField(default=0)),
                ('game_link', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='members',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
