# Generated by Django 4.2.16 on 2025-04-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_leaderboard_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='allow_bonus_alert',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='allow_missed_challenge_alert',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='allow_system_alert',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='allow_tournament_alert',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
