# Generated by Django 4.0.2 on 2023-01-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_available_players_members_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='user_game_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='is_available',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='uploaded_photo',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
