# Generated by Django 4.2.16 on 2025-04-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_members_allow_bonus_alert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='available_players',
            name='allow_player_search',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='balance_visibility_privacy',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='game_invite_privacy',
            field=models.CharField(blank=True, default='All', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='profile_visibility_privacy',
            field=models.CharField(blank=True, default='All', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='username_search_visibility_privacy',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
