# Generated by Django 4.0.2 on 2023-01-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_members_user_game_link_alter_members_is_available_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile_Photo',
            new_name='Profile_Photos',
        ),
        migrations.RemoveField(
            model_name='members',
            name='profile_photo',
        ),
        migrations.AddField(
            model_name='members',
            name='profile_photo_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='available_players',
            name='game_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='available_players',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='available_players_photos'),
        ),
        migrations.AlterField(
            model_name='available_players',
            name='stake_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='available_players',
            name='username',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='available_players',
            name='win_ratio',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
