# Generated by Django 4.0.2 on 2023-01-13 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_profile_photo_profile_photos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='available_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
