# Generated by Django 4.2.16 on 2025-04-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_available_players_allow_player_search_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='balance_visibility_privacy',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
