# Generated by Django 4.0.2 on 2023-01-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_members_available_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile_Photos',
        ),
        migrations.RemoveField(
            model_name='members',
            name='profile_photo_id',
        ),
        migrations.AddField(
            model_name='members',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photo'),
        ),
    ]
