# Generated by Django 4.2.16 on 2025-04-19 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_members_balance_visibility_privacy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='available_players',
            old_name='whatsapp_link',
            new_name='chat_link',
        ),
        migrations.RemoveField(
            model_name='available_players',
            name='uploaded_photo',
        ),
    ]
