# Generated by Django 4.0.2 on 2023-01-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_delete_profile_photos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='available_players',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='available_players',
            name='uploaded_photo',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
