# Generated by Django 4.2.16 on 2025-04-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_whatsapp_link_available_players_chat_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='available_players',
            name='country',
            field=models.CharField(blank=True, default='Nigeria', max_length=10000, null=True),
        ),
    ]
