# Generated by Django 4.2.16 on 2025-04-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_available_players_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='can_transfer',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
