# Generated by Django 4.0.2 on 2023-01-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_available_players_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='admin_charge',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='has_transfer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
