# Generated by Django 4.2.16 on 2025-04-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_members_can_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='available_players',
            name='format_stake_amount',
            field=models.CharField(blank=True, default='Nigeria', max_length=10000, null=True),
        ),
    ]
