# Generated by Django 4.0.2 on 2023-01-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_members_admin_charge_members_has_transfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='All_Profile_photos')),
            ],
        ),
        migrations.RemoveField(
            model_name='members',
            name='profile_photo',
        ),
        migrations.AddField(
            model_name='members',
            name='profile_photo',
            field=models.ManyToManyField(blank=True, to='main.Profile_Photos'),
        ),
    ]
