# Generated by Django 4.2.16 on 2025-04-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_available_players_format_stake_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available_players',
            name='format_stake_amount',
            field=models.CharField(blank=True, default=0, max_length=10000, null=True),
        ),
    ]
