# Generated by Django 4.0.2 on 2023-01-15 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_profile_photos_remove_members_profile_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='available_players',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='members',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='members',
            name='uploaded_photo',
        ),
        migrations.DeleteModel(
            name='Profile_Photos',
        ),
    ]
