# Generated by Django 4.0.2 on 2023-01-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_available_players_profile_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer_history',
            name='amount',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='transfer_history',
            name='charges',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
