# Generated by Django 4.2.16 on 2025-04-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_available_players_format_stake_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='highest_loss',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='highest_win',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
