# Generated by Django 4.0.2 on 2023-01-27 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_transfer_history_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenger', models.CharField(blank=True, max_length=1000, null=True)),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('challenged', models.CharField(blank=True, max_length=1000, null=True)),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='members',
            name='my_challenges',
            field=models.ManyToManyField(blank=True, to='main.Challenges'),
        ),
    ]
