# Generated by Django 4.2.16 on 2025-04-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_members_highest_loss_members_highest_win'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(blank=True, max_length=1000, null=True)),
                ('receiver', models.CharField(blank=True, max_length=1000, null=True)),
                ('message', models.TextField(blank=True, default="Hey,Let's Play Gold...", null=True)),
                ('is_seen', models.BooleanField(blank=True, default=False, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='All_Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_one', models.CharField(blank=True, max_length=1000, null=True)),
                ('chat_two', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('messages', models.ManyToManyField(blank=True, to='main.all_messages')),
            ],
        ),
        migrations.AddField(
            model_name='members',
            name='my_chats',
            field=models.ManyToManyField(blank=True, to='main.all_chats'),
        ),
    ]
