# Generated by Django 4.2.16 on 2025-04-24 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_all_messages_all_chats_members_my_chats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_messages',
            name='receiver',
        ),
    ]
