# Generated by Django 4.0.2 on 2023-02-06 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_challenges_members_my_challenges'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='current_opponent',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='has_game',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
