# Generated by Django 5.2 on 2025-04-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_all_messages_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_messages',
            name='receiver',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
