# Generated by Django 4.0.2 on 2023-02-06 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_members_current_opponent_members_has_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='game_expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
