# Generated by Django 4.0.2 on 2023-02-06 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_members_game_expiry_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='game_expiry_time',
            new_name='challenge_expiry_time',
        ),
    ]
