# Generated by Django 5.2 on 2025-04-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_all_messages_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='game_invite_privacy',
            field=models.BooleanField(blank=True, default=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='profile_visibility_privacy',
            field=models.BooleanField(blank=True, default=True, max_length=1000, null=True),
        ),
    ]
