# Generated by Django 5.2 on 2025-04-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_members_game_invite_privacy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='current_room_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
