# Generated by Django 4.0.2 on 2023-02-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_rename_game_expiry_time_members_challenge_expiry_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='is_challenger',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
