# Generated by Django 4.0.2 on 2023-02-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_members_is_challenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='current_challenge_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
