# Generated by Django 5.2 on 2025-04-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_members_current_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_chats',
            name='last_message_seen',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
