# Generated by Django 5.2 on 2025-04-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_all_chats_last_message_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_chats',
            name='last_sender',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
