# Generated by Django 4.0.2 on 2023-02-11 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_members_current_challenge_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='game_started',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
