# Generated by Django 4.0.2 on 2023-02-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_members_game_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='current_game_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
