# Generated by Django 5.2 on 2025-05-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_all_chats_last_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='allow_game_reload',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
