# Generated by Django 4.0.2 on 2023-02-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_members_current_game_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_registered_members', models.IntegerField(blank=True, default=0, null=True)),
                ('game_charges', models.IntegerField(blank=True, default=50, null=True)),
                ('transfer_charges', models.IntegerField(blank=True, default=100, null=True)),
                ('withdrawal_charges', models.IntegerField(blank=True, default=100, null=True)),
            ],
        ),
    ]
