# Generated by Django 5.2 on 2025-05-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_members_allow_game_reload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='allow_tournament_alert',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
