# Generated by Django 5.2 on 2025-05-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_members_allow_tournament_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='deposit_in_progress',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
