# Generated by Django 4.0.2 on 2023-02-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_admin_setup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_setup',
            old_name='game_charges',
            new_name='max_game_charges',
        ),
        migrations.AddField(
            model_name='admin_setup',
            name='min_game_charges',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
    ]
