# Generated by Django 4.0.2 on 2023-02-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_rename_game_charges_admin_setup_max_game_charges_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_setup',
            name='max_game_charges',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
