# Generated by Django 5.2 on 2025-05-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_withdrawals'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='my_withdrawals',
            field=models.ManyToManyField(blank=True, to='main.withdrawals'),
        ),
    ]
