# Generated by Django 4.0.2 on 2023-02-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_about_terms_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='step',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terms_condition',
            name='rule',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
