# Generated by Django 4.0.2 on 2023-02-21 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_about_step_terms_condition_rule'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='About_Game',
        ),
        migrations.RenameModel(
            old_name='Terms_Condition',
            new_name='Term_Condition',
        ),
    ]
