# Generated by Django 4.0.2 on 2023-02-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_rename_about_about_game_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_game',
            name='step',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='term_condition',
            name='rule',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
