# Generated by Django 4.0.2 on 2023-02-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_about_game_step_alter_term_condition_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='current_game_wining_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
