# Generated by Django 4.0.2 on 2023-03-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_members_current_game_wining_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='number_of_draw',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
