# Generated by Django 4.0.2 on 2023-03-01 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_members_number_of_draw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_Delay_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter', models.CharField(blank=True, max_length=1000, null=True)),
                ('report', models.CharField(blank=True, max_length=1000, null=True)),
                ('time_reported', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='members',
            name='number_of_reports',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='report_history',
            field=models.ManyToManyField(blank=True, to='main.Game_Delay_Report'),
        ),
    ]
