# Generated by Django 4.0.2 on 2023-03-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_game_delay_report_members_number_of_reports_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_setup',
            name='deposit_link',
            field=models.CharField(blank=True, default='https://wa.me/9038481789?text=Hi%20Please%20I%20Want%20To%20Deposit', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='admin_setup',
            name='withdrawal_link',
            field=models.CharField(blank=True, default='https://wa.me/9038481789?text=Hi%20Please%20I%20Want%20To%20Withdraw', max_length=1000, null=True),
        ),
    ]
