# Generated by Django 4.0.2 on 2023-03-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_admin_setup_deposit_link_admin_setup_withdrawal_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='phone_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
