# Generated by Django 4.0.2 on 2023-03-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_members_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='phone_number',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
