# Generated by Django 4.0.2 on 2023-03-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_admin_setup_deposit_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='balance',
            field=models.FloatField(blank=True, default=200, null=True),
        ),
    ]
