# Generated by Django 4.0.2 on 2023-03-25 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_members_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='available_players',
            name='time_available',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
