# Generated by Django 4.0.2 on 2023-03-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_available_players_time_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='missed_challenges',
            field=models.ManyToManyField(blank=True, related_name='Missed_Challenges', to='main.Challenges'),
        ),
        migrations.AlterField(
            model_name='members',
            name='my_challenges',
            field=models.ManyToManyField(blank=True, related_name='My_Challenges', to='main.Challenges'),
        ),
    ]
