# Generated by Django 4.0.2 on 2023-03-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_members_missed_challenges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='has_clicked_missed_challenges',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
