# Generated by Django 4.0.2 on 2023-03-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_members_has_clicked_missed_challenges'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='is_blacklisted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
