# Generated by Django 4.0.2 on 2023-04-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_members_current_game_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='current_number_of_whott_cards',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
