# Generated by Django 4.0.2 on 2023-05-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_members_current_number_of_whott_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_setup',
            name='no_of_golden_Whot_played',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='admin_setup',
            name='no_of_golden_number_played',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
