# Generated by Django 4.0.2 on 2023-05-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_admin_setup_no_of_golden_whot_played_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='balance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
