# Generated by Django 4.0.2 on 2023-05-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_alter_members_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_setup',
            name='today',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='admin_setup',
            name='today_number_of_games',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
