# Generated by Django 4.0.2 on 2023-06-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_admin_setup_today_admin_setup_today_number_of_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='available_players',
            name='whatsapp_link',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
