# Generated by Django 4.0.2 on 2024-05-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_available_players_whatsapp_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_setup',
            name='admin_whot_game_time',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
    ]
