# Generated by Django 4.0.2 on 2024-05-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_admin_setup_admin_whot_game_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_setup',
            name='admin_whot_game_time',
        ),
        migrations.AddField(
            model_name='members',
            name='initial_password',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='is_special',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='shuffling_check',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='members',
            name='shuffling_starting_game_on_progress',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
