# Generated by Django 4.0.2 on 2024-05-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_remove_admin_setup_admin_whot_game_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_setup',
            name='admin_whot_game_time',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
    ]
