# Generated by Django 4.0.2 on 2024-05-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_admin_setup_admin_whot_game_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer_history',
            name='net_balance',
            field=models.CharField(blank=True, default='Out-Dated', max_length=1000, null=True),
        ),
    ]
