# Generated by Django 4.0.2 on 2024-05-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_transfer_history_net_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_setup',
            name='admin_international_registration_link',
            field=models.CharField(blank=True, default='https://wa.me/7019462683?text=Hi,Not%20A%20Nigerian,%20Please%20I%20Want%20To%20Register', max_length=1000, null=True),
        ),
    ]
