# Generated by Django 4.0.2 on 2024-05-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_admin_setup_admin_international_registration_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_Phone_Numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=1000, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
