# Generated by Django 4.0.2 on 2024-06-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_all_phone_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='balance',
            field=models.FloatField(blank=True, default=200, null=True),
        ),
    ]
