# Generated by Django 4.0.2 on 2023-02-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GTT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_round', models.CharField(blank=True, default='First Round', max_length=1000, null=True)),
                ('player_one', models.CharField(blank=True, max_length=1000, null=True)),
                ('player_two', models.CharField(blank=True, max_length=1000, null=True)),
                ('player_one_count', models.IntegerField(blank=True, default=0, null=True)),
                ('player_two_count', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
