# Generated by Django 4.2.16 on 2025-04-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GTT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('game_round', models.IntegerField(blank=True, default=1, null=True)),
                ('player_one', models.CharField(blank=True, max_length=1000, null=True)),
                ('player_two', models.CharField(blank=True, max_length=1000, null=True)),
                ('player_one_count', models.IntegerField(blank=True, default=0, null=True)),
                ('player_two_count', models.IntegerField(blank=True, default=0, null=True)),
                ('to_send', models.CharField(blank=True, max_length=1000, null=True)),
                ('has_sent', models.BooleanField(blank=True, default=False, null=True)),
                ('to_receive', models.CharField(blank=True, max_length=1000, null=True)),
                ('has_received', models.BooleanField(blank=True, default=False, null=True)),
                ('receiver_number', models.IntegerField(blank=True, default=0, null=True)),
                ('not_found_winner', models.BooleanField(blank=True, default=True, null=True)),
                ('game_winner', models.CharField(blank=True, default='unknown', max_length=1000, null=True)),
                ('game_charges', models.IntegerField(blank=True, default=0, null=True)),
                ('game_wining_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('current_first_number', models.IntegerField(blank=True, default=0, null=True)),
                ('current_game_sign', models.CharField(blank=True, max_length=1000, null=True)),
                ('current_second_number', models.IntegerField(blank=True, default=0, null=True)),
                ('current_golden_number', models.IntegerField(blank=True, default=0, null=True)),
                ('current_random_number', models.IntegerField(blank=True, default=0, null=True)),
                ('current_second_random_number', models.IntegerField(blank=True, default=0, null=True)),
                ('current_third_random_number', models.IntegerField(blank=True, default=0, null=True)),
                ('has_tie', models.BooleanField(blank=True, default=False, null=True)),
                ('has_finished', models.BooleanField(blank=True, default=False, null=True)),
                ('result_collated', models.BooleanField(blank=True, default=False, null=True)),
                ('game_reload', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
