# Generated by Django 4.0.2 on 2023-02-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gtt',
            name='game_round',
            field=models.CharField(blank=True, default='First', max_length=1000, null=True),
        ),
    ]
