# Generated by Django 4.0.2 on 2023-02-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_gtt_game_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtt',
            name='to_play',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
