# Generated by Django 4.0.2 on 2023-02-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_gtt_to_play'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gtt',
            name='game_round',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
