# Generated by Django 4.0.2 on 2023-02-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_gtt_game_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtt',
            name='game_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
