# Generated by Django 4.0.2 on 2023-02-17 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_gtt_game_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtt',
            name='game_charges',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='gtt',
            name='game_winner',
            field=models.CharField(blank=True, default='unknown', max_length=1000, null=True),
        ),
    ]
