# Generated by Django 4.0.2 on 2023-02-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_gtt_game_charges_gtt_game_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtt',
            name='game_wining_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
