# Generated by Django 4.0.2 on 2023-02-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_gtt_game_wining_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gtt',
            old_name='to_play',
            new_name='to_receive',
        ),
        migrations.AddField(
            model_name='gtt',
            name='to_send',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
