# Generated by Django 4.0.2 on 2023-02-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_rename_to_play_gtt_to_receive_gtt_to_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtt',
            name='current_first_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='gtt',
            name='current_game_sign',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='gtt',
            name='current_golden_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='gtt',
            name='current_random_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='gtt',
            name='current_second_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
