# Generated by Django 4.0.2 on 2023-02-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_gtt_current_first_number_gtt_current_game_sign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtt',
            name='has_received',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='gtt',
            name='has_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
