# Generated by Django 4.0.2 on 2023-02-27 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_gtt_has_received_gtt_has_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtt',
            name='receiver_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
