# Generated by Django 4.0.2 on 2023-02-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_gtt_receiver_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gtt',
            name='game_round',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
