# Generated by Django 4.0.2 on 2023-02-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_alter_gtt_game_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtt',
            name='has_finished',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='gtt',
            name='has_tie',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
