# Generated by Django 4.0.2 on 2023-02-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_gtt_result_collated'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtt',
            name='a_winner',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
