# Generated by Django 4.0.2 on 2023-02-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_gtt_a_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gtt',
            name='a_winner',
        ),
        migrations.AddField(
            model_name='gtt',
            name='not_found_winner',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
