# Generated by Django 4.0.2 on 2023-03-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_remove_gtt_a_winner_gtt_not_found_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='gtt',
            name='game_reload',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
